### ISSUE TITLE
Application Bundle of OSX

### ISSUE THREAD

**Issue by cultpenguin** [ergosimulation/mpslib#1]
It would be nice to distribute compiled binaries for OS-X that works wihtout XCode being being installed.

**Comment by vutit** [comment]
I don't have a Mac to be able to do that, do you have one ? I don't think there would be a big challenge to compile on OS-X as the code is using standard C++ and no external dependencies.

**Comment by cultpenguin** [comment]
Hi Vu
The thing is..
You cannot do a 'static compilation' on OSX using GCC as you can on
windows/linux. So, you have to either assume the user has XCODE installed,
or distribute the linked libraries in a self contained OSX package..
The last option would be best.
- Thomas
---------- Forwarded message ----------

**Comment by cultpenguin** [comment]
This has not been requested
