### ISSUE TITLE
Reconstruct 3d image from a single 2d image

### ISSUE THREAD

**Issue by Abolfazlmsl** [ergosimulation/mpslib#12]
Hello,
when i reconstruct a 3D image from a single 2D image, it doesnt have good connectivity in z direction. How i can reconstruct a 3D image from a single 2D image with mpslib?
Thanks for your help
best regards,
Abolfazl

**Comment by cultpenguin** [comment]
In general, you cannot reconstruct a 3D image from a single 2D image only, as you lack information about the statistics in the 3rd direction (using mpslib or any other simulation algorithm) .  You will have to make some additional assumptions. 

For more on this topic check out  "3D multiple-point statistics simulation using 2D training images" --> [https://doi.org/10.1016/j.cageo.2011.07.009](https://doi.org/10.1016/j.cageo.2011.07.009)
