### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by somethingforheheda** [ergosimulation/mpslib#18]
ENESIM.cpp
line:417 
originally:
if (i_ti_path>_tiPath.size()) {
it shoule be:
if (i_ti_path>=_tiPath.size()) {

when the i_ti_path is equal to _tiPath.size(), it should also subtract the length of the array to 0, otherwise the array will be out of bounds

**Comment by cultpenguin** [comment]
Thank you. This is now fixed
