### ISSUE TITLE
NEW TO MPSLIB

### ISSUE THREAD

**Issue by jbensabat** [ergosimulation/mpslib#19]
Hello 
I am trying to use the library and I have two questions that I would be grateful if you could address.

1.  the user has to provide a training image. Does it have to be a full image (nx*ny data points in 2D or nx*ny*nz data points in 3D) ? Is it possible to provide a set of data points only (data at sampling locations) ?
2. Is it possible to work with a continuous variable instead of a categorical variable ?

thanks 
jac

**Comment by cultpenguin** [comment]
Hi Jac.
You can use a sparse training image with mps_snesim_tree and mps_snesim_list. See an example here:
https://github.com/ergosimulation/mpslib/blob/master/scikit-mps/examples/ex_sparse_ti.ipynb
I will test if this applies to mps_genesim as well.

You can use a continuous training image with mps_genesim. 
You need to set

     O.par['distance_measure'] # Distance measure [1]: discrete, [2]: continous
     O.par['distance_max'] ; # Max distance
     O.par['distance_pow'] ; # Power

See an example here:
https://github.com/ergosimulation/mpslib/blob/master/scikit-mps/examples/ex_genesim_continuous.ipynb

**Comment by cultpenguin** [comment]
I only just added the example of using a sparse TI. If you make some nice examples of the use of MPSlib feel free to add them or send them to me and I will.
- Thomas
